export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_CREATED_FAILURE = 'USER_CREATED_FAILURE';

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export const USER_EXIST_SUCCESS = 'USER_EXIST_SUCCESS';
export const USER_EXIST_FAILURE = 'USER_EXIST_FAILURE';

export const SET_VALIDATION_STATE = 'SET_VALIDATION_STATE';

export const USER_EXIST_FALSE='USER_EXIST_FALSE';

export const POST_CREATED_SUCCESS='POST_CREATED_SUCCESS';
export const POST_CREATED_FAILURE='POST_CREATED_SUCCESS';

export const FETCH_EXERCISE_SUCCESS="FETCH_EXERCISE_SUCCESS";
export const FETCH_EXERCISE_FAILURE="FETCH_EXERCISE_FAILURE";


export const FETCH_EXERCISESLIST_SUCCESS="FETCH_EXERCISESLIST_SUCCESS";
export const FETCH_EXERCISESLIST_FAILURE="FETCH_EXERCISESLIST_FAILURE";

export const CLEAR_SCHEDULE_LIST = "CLEAR_SCHEDULE_LIST";
export const ADD_TO_SCHEDULE_LIST ="ADD_TO_SCHEDULE_LIST";