export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_CREATED_FAILURE = 'USER_CREATED_FAILURE';

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export const USER_EXIST_SUCCESS = 'USER_EXIST_SUCCESS';
export const USER_EXIST_FAILURE = 'USER_EXIST_FAILURE';

export const SET_VALIDATION_STATE = 'SET_VALIDATION_STATE';

export const USER_EXIST_FALSE='USER_EXIST_FALSE';

export const POST_CREATED_SUCCESS='POST_CREATED_SUCCESS';
export const POST_CREATED_FAILURE='POST_CREATED_SUCCESS';
