/**
 * Created by sourabh on 27/6/17.
 */

export const USER_CREATED_SUCCESS="USER_CREATED_SUCCESS";
export const USER_CREATED_FAILURE="USER_CREATED_FAILURE";

export const AUTHENTICATE_USER_SUCCESS="AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_FAILURE="AUTHENTICATE_USER_FAILURE";


